### ISSUE TITLE
抽象网络训练，网络架构任然是 GAN吗？，没有明白，怎么反过来，由真实图片训练输出得到带有纹理信息的脸部抽象分割图

### ISSUE THREAD

**Issue by shiyuanyin** [TencentYoutuResearch/FaceAttribute-FAN#2]
您好作者，
我看了您的论文，对于抽象网络的训练没有看的很明白，想要请教下您
We train face abstraction  model  on  the  training  images.   To  generate  the ground truth abstraction images, we use the codes of [Liuet al., 2015a]
which saves the textual information.  To train the facial abstraction model,  we use the codes of [
Wang et al.,2017a].  As our GAN learns the distribution of training data (including textual information), we can generate images with textual information.
网络架构任然是 GAN吗？，没有明白，怎么反过来，由真实图片训练输出得到带有纹理信息的脸部抽象分割图

**Comment by qiexing** [comment]
@shiyuanyin 您好，抽象网络的训练是gan。如论文中所说的：先用[Liuet al., 2015a]中的代码生成gt的抽象图。然后用原图和gt抽象图来训练gan网络。

**Comment by DanielXu123** [comment]
@qiexing Hello, qiexing

想再确认下, 这个GAN是用Helen 数据集训练的吗?

"先用[Liuet al., 2015a]中的代码"

这个代码能提供一个链接参考学习一下吗?

**Comment by DanielXu123** [comment]
@shiyuanyin hello, yuanyin, 想问一下, 这个训练的脚本你有成功跑起来吗?

**Comment by sky186** [comment]
@能，好像有点改动，可以跑的，你看出现什么问题，自己调整下，因该就可以了

**Comment by DanielXu123** [comment]
@sky186 
sky, 你好, 我这边能正常得跑作者提供的测试的脚本(理应这个可以证明caffe安装的是没有问题). 但是训练的脚本跑不起来. 
按照作者的READme 中的描述
在~/FaceAttribute-FAN/models/dual_path_parse_resnet 执行 train.sh

遇到的这个问题
I1031 01:53:39.988425 30360 layer_factory.hpp:77] Creating layer data
*** Aborted at 1572458021 (unix time) try "date -d @1572458021" if you are using GNU date ***
PC: @     0x7f3b97ced713 std::_Hashtable<>::clear()
*** SIGSEGV (@0xd) received by PID 30360 (TID 0x7f3c24846ac0) from PID 13; stack trace: ***
    @     0x7f3c010905f0 (unknown)
    @     0x7f3b97ced713 std::_Hashtable<>::clear()
    @     0x7f3b97cdcc18 google::protobuf::DescriptorPool::FindFileByName()
    @     0x7f3b97ca7548 (unknown)
    @     0x7f3c027e5cb2 PyEval_EvalFrameEx
    @     0x7f3c027e808d PyEval_EvalCodeEx
    @     0x7f3c02771abd (unknown)
    @     0x7f3c0274cab3 PyObject_Call
    @     0x7f3c0279f35d (unknown)
    @     0x7f3c027a27a3 (unknown)
    @     0x7f3c0274cab3 PyObject_Call
    @     0x7f3c027e1286 PyEval_EvalFrameEx
    @     0x7f3c027e808d PyEval_EvalCodeEx
    @     0x7f3c027e8192 PyEval_EvalCode
    @     0x7f3c027f7f7c PyImport_ExecCodeModuleEx
    @     0x7f3c027f81f8 (unknown)
    @     0x7f3c027f8e91 (unknown)
    @     0x7f3c027f938f (unknown)
    @     0x7f3c027f9bca PyImport_ImportModuleLevel
    @     0x7f3c027dcd6f (unknown)
    @     0x7f3c0274cab3 PyObject_Call
    @     0x7f3c027de947 PyEval_CallObjectWithKeywords
    @     0x7f3c027e3605 PyEval_EvalFrameEx
    @     0x7f3c027e808d PyEval_EvalCodeEx
    @     0x7f3c027e8192 PyEval_EvalCode
    @     0x7f3c027f7f7c PyImport_ExecCodeModuleEx
    @     0x7f3c027f81f8 (unknown)
    @     0x7f3c027f8e91 (unknown)
    @     0x7f3c027f90dd (unknown)
    @     0x7f3c027f9af8 PyImport_ImportModuleLevel
    @     0x7f3c027dcd6f (unknown)
    @     0x7f3c0274cab3 PyObject_Call

**Comment by DanielXu123** [comment]
好像是protobuf的问题. 想问一下,你的protobuf 是哪个版本的呢? @sky186

**Comment by shiyuanyin** [comment]
好像是2.6的那个版本，时间有点久了，记不清了环境变了很多次




------------------ 原始邮件 ------------------
发件人: "DanielXu123"<notifications@github.com>;
发送时间: 2019年10月30日(星期三) 中午11:09
收件人: "TencentYoutuResearch/FaceAttribute-FAN"<FaceAttribute-FAN@noreply.github.com>;
抄送: "史诗"<892781037@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [TencentYoutuResearch/FaceAttribute-FAN] 抽象网络训练，网络架构任然是 GAN吗？，没有明白，怎么反过来，由真实图片训练输出得到带有纹理信息的脸部抽象分割图 (#2)




好像是protobuf的问题. 想问一下,你的protobuf 是哪个版本的呢? @sky186

**Comment by DanielXu123** [comment]
我的caffe 安装的是2.6.1的。
然后之前不知道怎么改动了下，现在报了个错说
This program requires version 3.10.0 of the protocol buffer runtime library

那，这意味着，我要重新装个3.10.0再重新装下caffe ？？






Best wishes！


Daniel Xu
在2019年10月30日 11:11，happy 写道：
好像是2.6的那个版本，时间有点久了，记不清了环境变了很多次




------------------ 原始邮件 ------------------
发件人: "DanielXu123"<notifications@github.com>;
发送时间: 2019年10月30日(星期三) 中午11:09
收件人: "TencentYoutuResearch/FaceAttribute-FAN"<FaceAttribute-FAN@noreply.github.com>;
抄送: "史诗"<892781037@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [TencentYoutuResearch/FaceAttribute-FAN] 抽象网络训练，网络架构任然是 GAN吗？，没有明白，怎么反过来，由真实图片训练输出得到带有纹理信息的脸部抽象分割图 (#2)




好像是protobuf的问题. 想问一下,你的protobuf 是哪个版本的呢? @sky186

**Comment by DanielXu123** [comment]
@shiyuanyin Hello , 另外想问一下, 是否有试过不加GAN这一分支, 只单独跑CelebA 原图的效果?

**Comment by shiyuanyin** [comment]
------------------ 原始邮件 ------------------
发件人: "DanielXu123"<notifications@github.com>;
发送时间: 2019年10月30日(星期三) 下午3:32
收件人: "TencentYoutuResearch/FaceAttribute-FAN"<FaceAttribute-FAN@noreply.github.com>;
抄送: "史诗"<892781037@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [TencentYoutuResearch/FaceAttribute-FAN] 抽象网络训练，网络架构任然是 GAN吗？，没有明白，怎么反过来，由真实图片训练输出得到带有纹理信息的脸部抽象分割图 (#2)




@shiyuanyin Hello , 另外想问一下, 是否有试过不加GAN这一分支, 只单独跑CelebA 原图的效果?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.




有，可以跑的，精度好像略差一点，时间有点长对出现的问题解决没什么印象了，但是出现问题，我应该就是百度解决的，没其他

**Comment by DanielXu123** [comment]
@shiyuanyin caffe  是用的caffe2???


}
layer {
  name: "res5a_branch2b_relu"
  type: "ReLU"
  bottom: "res5a_branch2b"
  top: "res5a_branch2b"
}
layer {
  name: "res5a_branch2c"
  type: "Convolution"
  bottom: "res5a_branch2b"
  top: "res5a_branch2c"
  convolution_param {
    num_output: 2048
    bia
I1031 09:23:44.403954 26173 layer_factory.hpp:77] Creating layer data
Traceback (most recent call last):
  File "~/FaceAttribute-FAN/models/dual_path_parse_resnet/python_data_layer.py", line 3, in<module>
    import caffe
  File "~/caffe-1.0/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "~/caffe-1.0/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "~/caffe-1.0/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "~/caffe-1.0/python/caffe/proto/caffe_pb2.py", line 24, in <module>
    t_bg_threshold\x18\x37 \x01(\x02:\x03\x30.5\x12\x1d\n\x0f\x64\x65t_fg_fraction\x18\x38 \x01(\x02:\x04\x30.25\x12\x1a\n\x0f\x64\x65t_context_pad\x18: \x01(\r:\x01\x30\x12\x1b\n\rdet_crop_mode\x18; \x01(\t:\x04warp\x12\x12\n\x07new_num\x18< \x01(\x05:\x01\x30\x12\x17\n\x0cnew_channels\x18= \x01(\x05:\x01\x30\x12\x15\n\nnew_height\x18> \x01(\x05:\x01\x30\x12\x14\n\tnew_width\x18? \x01(\x05:\x01\x30\x12\x1d\n\x0eshuffle_images\x18@ \x01(\x08:\x05\x66\x61lse\x12\x15\n\nconcat_dim\x18\x41 \x01(\r:\x01\x31\x12\x36\n\x11hdf5_output_param\x18\xe9\x07 \x01(\x0b\x32\x1a.caffe.HDF5OutputParameter\".\n\nPoolMethod\x12\x07\n\x03MAX\x10\x00\x12\x07\n\x03\x41VE\x10\x01\x12\x0e\n\nSTOCHASTIC\x10\x02\"W\n\x0ePReLUParameter\x12&\n\x06\x66iller\x18\x01 \x01(\x0b\x32\x16.caffe.FillerParameter\x12\x1d\n\x0e\x63hannel_shared\x18\x02 \x01(\x08:\x05\x66\x61lse*\x1c\n\x05Phase\x12\t\n\x05TRAIN\x10\x00\x12\x08\n\x04TEST\x10\x01')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
