### ISSUE TITLE
How to generate a facial abstract image from an original face?

### ISSUE THREAD

**Issue by jhss** [TencentYoutuResearch/FaceAttribute-FAN#3]
Could I use dual path only for celebA dataset? Is there any way to generate an abstract face from my own data set and use that image as a dual path input?

**Comment by qiexing** [comment]
@jhss Yes, later will upload a gan model which can generate a abstract face from original image.

**Comment by sycyjl7146** [comment]
hi, where can I get  the  gan model which can generate a abstract face from original image, thx

**Comment by DanielXu123** [comment]
同问. 这个GAN模型训练方法,能否也能介绍一下.谢谢!
